# fly.toml app configuration file generated for breath-first-search on 2023-10-17T03:52:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ollama-docker"
primary_region = "arn"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
